<?php

    function obterBandeiraPais(string $nomePais): string 
    {
        $paisNorm = mb_strtolower(trim($nomePais), 'UTF-8');
        
        $bandeiras = [
            "afeganistão" => "af", "afeganistao" => "af", "afghanistan" => "af", "アフガニスタン" => "af",
            "áfrica do sul" => "za", "africa do sul" => "za", "south africa" => "za", "南アフリカ" => "za",
            "albânia" => "al", "albania" => "al", "アルバニア" => "al",
            "alemanha" => "de", "germany" => "de", "ドイツ" => "de",
            "andorra" => "ad", "アンドラ" => "ad",
            "angola" => "ao", "アンゴラ" => "ao",
            "antígua e barbuda" => "ag", "antigua e barbuda" => "ag", "antigua and barbuda" => "ag", "アンティグア・バーブーダ" => "ag",
            "arábia saudita" => "sa", "arabia saudita" => "sa", "saudi arabia" => "sa", "サウジアラビア" => "sa",
            "argélia" => "dz", "argelia" => "dz", "algeria" => "dz", "アルジェリア" => "dz",
            "argentina" => "ar", "アルゼンチン" => "ar",
            "armênia" => "am", "armenia" => "am", "アルメニア" => "am",
            "austrália" => "au", "australia" => "au", "オーストラリア" => "au",
            "áustria" => "at", "austria" => "at", "オーストリア" => "at",
            "azerbaijão" => "az", "azerbaijao" => "az", "azerbaijan" => "az", "アゼルバイジャン" => "az",
            "bahamas" => "bs", "バハマ" => "bs",
            "bangladesh" => "bd", "バングラデシュ" => "bd",
            "barbados" => "bb", "バルバドス" => "bb",
            "bahrein" => "bh", "bahrain" => "bh", "バーレーン" => "bh",
            "bielorrússia" => "by", "bielorrussia" => "by", "belarus" => "by", "ベラルーシ" => "by",
            "bélgica" => "be", "belgica" => "be", "belgium" => "be", "ベルギー" => "be",
            "belize" => "bz", "ベリーズ" => "bz",
            "benin" => "bj", "ベナン" => "bj",
            "butão" => "bt", "butao" => "bt", "bhutan" => "bt", "ブータン" => "bt",
            "bolívia" => "bo", "bolivia" => "bo", "ボリビア" => "bo",
            "bósnia e herzegovina" => "ba", "bosnia and herzegovina" => "ba", "ボスニア・ヘルツェゴビナ" => "ba",
            "botsuana" => "bw", "botswana" => "bw", "ボツワナ" => "bw",
            "brasil" => "br", "brazil" => "br", "ブラジル" => "br",
            "brunei" => "bn", "ブルネイ" => "bn",
            "bulgária" => "bg", "bulgaria" => "bg", "ブルガリア" => "bg",
            "burkina faso" => "bf", "ブルキナファソ" => "bf",
            "burundi" => "bi", "ブルンジ" => "bi",
            "cabo verde" => "cv", "cape verde" => "cv", "カーボベルデ" => "cv",
            "camarões" => "cm", "camaroes" => "cm", "cameroon" => "cm", "カメルーン" => "cm",
            "camboja" => "kh", "cambodia" => "kh", "カンボジア" => "kh",
            "canadá" => "ca", "canada" => "ca", "カナダ" => "ca",
            "catar" => "qa", "qatar" => "qa", "カタール" => "qa",
            "cazaquistão" => "kz", "cazaquistao" => "kz", "kazakhstan" => "kz", "カザフスタン" => "kz",
            "chade" => "td", "chad" => "td", "チャド" => "td",
            "chile" => "cl", "チリ" => "cl",
            "china" => "cn", "中国" => "cn",
            "chipre" => "cy", "cyprus" => "cy", "キプロス" => "cy",
            "colômbia" => "co", "colombia" => "co", "コロムビア" => "co",
            "comores" => "km", "comoros" => "km", "コモロ" => "km",
            "congo-brazzaville" => "cg", "republic of the congo" => "cg", "コンゴ共和国" => "cg",
            "congo-kinshasa" => "cd", "democratic republic of the congo" => "cd", "コンゴ民主共和国" => "cd",
            "coreia do norte" => "kp", "north korea" => "kp", "北朝鮮" => "kp",
            "coreia do sul" => "kr", "south korea" => "kr", "韓国" => "kr",
            "costa do marfim" => "ci", "cote d'ivoire" => "ci", "ivory coast" => "ci", "コートジボワール" => "ci",
            "costa rica" => "cr", "コスタリカ" => "cr",
            "croácia" => "hr", "croacia" => "hr", "croatia" => "hr", "クロアチア" => "hr",
            "cuba" => "cu", "キューバ" => "cu",
            "dinamarca" => "dk", "denmark" => "dk", "デンマーク" => "dk",
            "djibouti" => "dj", "ジブチ" => "dj",
            "dominica" => "dm", "ドミニカ国" => "dm",
            "egito" => "eg", "egypt" => "eg", "エジプト" => "eg",
            "el salvador" => "sv", "エルサルバドル" => "sv",
            "emirados árabes unidos" => "ae", "united arab emirates" => "ae", "アラブ首長国連邦" => "ae",
            "estados unidos" => "us", "eua" => "us", "united states" => "us", "アメリカ" => "us", 
            "equador" => "ec", "ecuador" => "ec", "エクアドル" => "ec",
            "eritreia" => "er", "eritrea" => "er", "エリトリア" => "er",
            "eslováquia" => "sk", "slovakia" => "sk", "スロバキア" => "sk",
            "eslovênia" => "si", "slovenia" => "si", "スロベニア" => "si",
            "espanha" => "es", "spain" => "es", "スペイン" => "es",
            "estônia" => "ee", "estonia" => "ee", "エストニア" => "ee",
            "eswatini" => "sz", "swaziland" => "sz", "エスワティニ" => "sz",
            "etiópia" => "et", "ethiopia" => "et", "エチオピア" => "et",
            "fiji" => "fj", "フィジー" => "fj",
            "filipinas" => "ph", "philippines" => "ph", "フィリピン" => "ph",
            "finlândia" => "fi", "finland" => "fi", "フィンランド" => "fi",
            "frança" => "fr", "france" => "fr", "フランス" => "fr",
            "gabão" => "ga", "gabon" => "ga", "ガボン" => "ga",
            "gâmbia" => "gm", "gambia" => "gm", "ガンビア" => "gm",
            "gana" => "gh", "ghana" => "gh", "ガーナ" => "gh",
            "geórgia" => "ge", "georgia" => "ge", "ジョージア" => "ge",
            "granada" => "gd", "grenada" => "gd", "グレナダ" => "gd",
            "grécia" => "gr", "greece" => "gr", "ギリシャ" => "gr",
            "guatemala" => "gt", "グアテマラ" => "gt",
            "guiana" => "gy", "guyana" => "gy", "ガイアナ" => "gy",
            "guiné" => "gn", "guinea" => "gn", "ギニア" => "gn",
            "guiné equatorial" => "gq", "equatorial guinea" => "gq", "赤道ギニア" => "gq",
            "guiné-bissau" => "gw", "guinea-bissau" => "gw", "ギニアビサウ" => "gw",
            "haiti" => "ht", "ハイチ" => "ht",
            "honduras" => "hn", "ホンジュラス" => "hn",
            "hungria" => "hu", "hungary" => "hu", "ハンガリー" => "hu",
            "iêmen" => "ye", "iemen" => "ye", "yemen" => "ye", "イエメン" => "ye",
            "ilhas marshall" => "mh", "marshall islands" => "mh", "マーシャル諸島" => "mh",

            "ilhas salomão" => "sb", "solomon islands" => "sb", "ソロモン諸島" => "sb",
            "índia" => "in", "india" => "in", "インド" => "in",
            "indonésia" => "id", "indonesia" => "id", "インドネシア" => "id",
            "irã" => "ir", "ira" => "ir", "iran" => "ir", "イラン" => "ir",
            "iraque" => "iq", "iraq" => "iq", "イラク" => "iq",
            "irlanda" => "ie", "ireland" => "ie", "アイルランド" => "ie",
            "islândia" => "is", "islandia" => "is", "iceland" => "is", "アイスランド" => "is",
            "israel" => "il", "イスラエル" => "il",
            "itália" => "it", "italia" => "it", "italy" => "it", "イタリア" => "it",
            "jamaica" => "jm", "ジャマイカ" => "jm",
            "japão" => "jp", "japao" => "jp", "japan" => "jp", "日本" => "jp",
            "jordânia" => "jo", "jordania" => "jo", "jordan" => "jo", "ヨルダン" => "jo",
            "kiribati" => "ki", "キリバス" => "ki",
            "kuwait" => "kw", "クウェート" => "kw",
            "laos" => "la", "ラオス" => "la",
            "lesoto" => "ls", "lesotho" => "ls", "レソト" => "ls",
            "letônia" => "lv", "letonia" => "lv", "latvia" => "lv", "ラトビア" => "lv",
            "líbano" => "lb", "libano" => "lb", "lebanon" => "lb", "レバノン" => "lb",
            "libéria" => "lr", "liberia" => "lr", "リベリア" => "lr",
            "líbia" => "ly", "libia" => "ly", "libya" => "ly", "リビア" => "ly",
            "liechtenstein" => "li", "リヒテンシュタイン" => "li",
            "lituânia" => "lt", "lituania" => "lt", "lithuania" => "lt", "リトアニア" => "lt",
            "luxemburgo" => "lu", "luxembourg" => "lu", "ルクセンブルク" => "lu",
            "macedônia do norte" => "mk", "north macedonia" => "mk", "北マケドニア" => "mk",
            "madagascar" => "mg", "マダガスカル" => "mg",
            "malásia" => "my", "malasia" => "my", "malaysia" => "my", "マレーシア" => "my",
            "malawi" => "mw", "マラウイ" => "mw",
            "maldivas" => "mv", "maldives" => "mv", "モルディブ" => "mv",
            "mali" => "ml", "マリ" => "ml",
            "malta" => "mt", "マルタ" => "mt",
            "marrocos" => "ma", "morocco" => "ma", "モロッコ" => "ma",
            "maurício" => "mu", "mauricio" => "mu", "mauritius" => "mu", "モーリシャス" => "mu",
            "mauritânia" => "mr", "mauritania" => "mr", "モーリタニア" => "mu",
            "méxico" => "mx", "mexico" => "mx", "メキシコ" => "mx",
            "mianmar" => "mm", "myanmar" => "mm", "ミャンマー" => "mm",
            "micronésia" => "fm", "micronesia" => "fm", "ミクロネシア" => "fm",
            "moçambique" => "mz", "mocambique" => "mz", "mozambique" => "mz", "モザンビーク" => "mz",
            "moldávia" => "md", "moldavia" => "md", "moldova" => "md", "モルドバ" => "md",
            "mônaco" => "mc", "monaco" => "mc", "モナコ" => "mc",
            "mongólia" => "mn", "mongolia" => "mn", "モンゴル" => "mn",
            "montenegro" => "me", "モンテネグロ" => "me",
            "namíbia" => "na", "namibia" => "na", "ナミビア" => "na",
            "nauru" => "nr", "ナウル" => "nr",
            "nepal" => "np", "ネパール" => "np",
            "nicarágua" => "ni", "nicaragua" => "ni", "ニカラグア" => "ni",
            "níger" => "ne", "niger" => "ne", "ニジェール" => "ne",
            "nigéria" => "ng", "nigeria" => "ng", "ナイジェリア" => "ng",
            "noruega" => "no", "norway" => "no", "ノルウェー" => "no",
            "nova zelândia" => "nz", "nova zelandia" => "nz", "new zealand" => "nz", "ニュージーランド" => "nz",
            "omã" => "om", "oma" => "om", "oman" => "om", "オマーン" => "om",
            "países baixos" => "nl", "paises baixos" => "nl", "netherlands" => "nl", "holanda" => "nl", "オランダ" => "nl",
            "palau" => "pw", "パラオ" => "pw",
            "panamá" => "pa", "panama" => "pa", "パナマ" => "pa",
            "papua nova guiné" => "pg", "papua new guinea" => "pg", "パプアニューギニア" => "pg",
            "paquistão" => "pk", "paquistao" => "pk", "pakistan" => "pk", "パキスタン" => "pk",
            "paraguai" => "py", "paraguay" => "py", "パラグアイ" => "py",
            "peru" => "pe", "ペルー" => "pe",
            "polônia" => "pl", "polonia" => "pl", "poland" => "pl", "ポーランド" => "pl",
            "portugal" => "pt", "ポルトガル" => "pt",
            "quênia" => "ke", "quenia" => "ke", "kenya" => "ke", "ケニア" => "ke",
            "quirguistão" => "kg", "kyrgyzstan" => "kg", "キルギス" => "kg",
            "reino unido" => "gb", "united kingdom" => "gb", "inglaterra" => "gb", "england" => "gb", "イギリス" => "gb",
            "república centro-africana" => "cf", "central african republic" => "cf", "中央アフリカ" => "cf",
            "república checa" => "cz", "czech republic" => "cz", "czechia" => "cz", "チェコ" => "cz",
            "república dominicana" => "do", "dominican republic" => "do", "ドミニカ共和国" => "do",
            "romênia" => "ro", "romenia" => "ro", "romania" => "ro", "ルーマニア" => "ro",
            "ruanda" => "rw", "rwanda" => "rw", "ルワンダ" => "rw",
            "rússia" => "ru", "russia" => "ru", "russian federation" => "ru", "ロシア" => "ru",
            "samoa" => "ws", "サモア" => "ws",
            "san marino" => "sm", "サンマリノ" => "sm",
            "santa lúcia" => "lc", "santa lucia" => "lc", "saint lucia" => "lc", "セントルシア" => "lc",
            "são cristóvão e nevis" => "kn", "saint kitts and nevis" => "kn", "セントクリストファー・ネイビス" => "kn",
            "são tomé e príncipe" => "st", "sao tome and principe" => "st", "サントメ・プリンシペ" => "st",
            "são vicente e granadinas" => "vc", "saint vincent and the grenadines" => "vc", "セントビンセント・グレナディーン" => "vc",
            "seychelles" => "sc", "セーシェル" => "sc",
            "senegal" => "sn", "セネガル" => "sn",
            "serra leoa" => "sl", "sierra leone" => "sl", "シエラレオネ" => "sl",
            "sérvia" => "rs", "servia" => "rs", "serbia" => "rs", "セルビア" => "rs",
            "singapura" => "sg", "singapore" => "sg", "シンガポール" => "sg",
            "síria" => "sy", "siria" => "sy", "syria" => "sy", "シリア" => "sy",
            "somália" => "so", "somalia" => "so", "ソマリア" => "so",
            "sri lanka" => "lk", "スリランカ" => "lk",
            "sudão" => "sd", "sudao" => "sd", "sudan" => "sd", "スーダン" => "sd",
            "sudão do sul" => "ss", "south sudan" => "ss", "南スーダン" => "ss",
            "suécia" => "se", "suecia" => "se", "sweden" => "se", "スウェーデン" => "se",
            "suíça" => "ch", "suica" => "ch", "switzerland" => "ch", "スイス" => "ch",
            "suriname" => "sr", "スリナム" => "sr",
            "tadjiquistão" => "tj", "tajikistan" => "tj", "タジキスタン" => "tj",
            "tailândia" => "th", "tailandia" => "th", "thailand" => "th", "タイ" => "th",
            "tanzânia" => "tz", "tanzania" => "tz", "タンザニア" => "tz",
            "timor-leste" => "tl", "東ティモール" => "tl",
            "togo" => "tg", "トーゴ" => "tg",
            "tonga" => "to", "トンガ" => "to",
            "trinidad e tobago" => "tt", "trinidad and tobago" => "tt", "トリニダード・トバゴ" => "tt",
            "tunísia" => "tn", "tunisia" => "tn", "チュニジア" => "tn",
            "turcomenistão" => "tm", "turkmenistan" => "tm", "トルクメニスタン" => "tm",
            "turquia" => "tr", "turkey" => "tr", "türkiye" => "tr", "トルコ" => "tr",
            "tuvalu" => "tv", "ツバル" => "tv",
            "ucrânia" => "ua", "ucrania" => "ua", "ukraine" => "ua", "ウクライナ" => "ua",
            "uganda" => "ug", "ウガンダ" => "ug",
            "uruguai" => "uy", "uruguay" => "uy", "ウルグアイ" => "uy",
            "uzbequistão" => "uz", "uzbekistan" => "uz", "ウズベキスタン" => "uz",
            "vanuatu" => "vu", "バヌアツ" => "vu",
            "vaticano" => "va", "vatican city" => "va", "holy see" => "va", "バチカン市国" => "va",
            "venezuela" => "ve", "ベネズエラ" => "ve",
            "vietnã" => "vn", "vietna" => "vn", "vietnam" => "vn", "ベトナム" => "vn",
            "zâmbia" => "zm", "zambia" => "zm", "ザンビア" => "zm",
            "zimbábue" => "zw", "zimbabue" => "zw", "zimbabwe" => "zw", "ジンバブエ" => "zw"
        ];

        if (array_key_exists($paisNorm, $bandeiras)) 
        {
            $iso = $bandeiras[$paisNorm];
            return '<span class="fi fi-' . $iso . ' me-1 shadow-sm" style="border-radius: 2px;"></span>';
        }
        
        return '<i class="fa-solid fa-earth-americas text-muted small me-1"></i>';
    }
?>